@echo off
cd /d e:\CogniDesk
echo Cleaning npm cache...
npm cache clean --force
echo Installing core dependencies...
npm install next@15.3.3 react@18.2.0 react-dom@18.2.0 --save
echo Installing dev dependencies...
npm install typescript@5.2.2 @types/node@20.9.0 @types/react@18.2.37 @types/react-dom@18.2.15 --save-dev
echo Installing build tools...
npm install postcss@8.4.31 autoprefixer@10.4.16 tailwindcss@3.3.5 --save-dev
echo Testing build...
npm run build
echo Done! If successful, you can now run: firebase deploy
pause