name: Deploy to Firebase App Hosting

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      NODE_VERSION: '18'
      FIREBASE_PROJECT_ID: studio-7308845117-ec2b2
      
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
          
    - name: Install dependencies
      run: npm ci
      
    - name: Run build
      env:
        NODE_ENV: production
        NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ env.FIREBASE_PROJECT_ID }}
        NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
        NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: studio-7308845117-ec2b2.firebaseapp.com
        NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: studio-7308845117-ec2b2.firebasestorage.app
        NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
        NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
      run: npm run build
      
    - name: Setup Firebase CLI
      uses: w9jds/setup-firebase@main
      with:
        tools: cli
        firebase_token: ${{ secrets.FIREBASE_TOKEN }}
        
    - name: Deploy to Firebase App Hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: |
        firebase apphosting:rollouts:create \
          --project ${{ env.FIREBASE_PROJECT_ID }} \
          --message "GitHub Actions deployment from commit ${{ github.sha }}"
          
    - name: Deploy status notification
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "✅ Deployment successful! 🚀"
          echo "🌐 App URL: https://studio-7308845117-ec2b2.web.app"
          echo "🔧 Firebase Console: https://console.firebase.google.com/project/studio-7308845117-ec2b2"
        else
          echo "❌ Deployment failed!"
        fi